name: Alignment


on:
  push:
    branches:
      - '**'

jobs:
  alignment:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.6.3
        id: generate-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Get the commit message header
        id: commit-message
        run: |
          HEADER=$(git log -1 --pretty=%B | head -n 1)
          echo "Commit message header: $HEADER"
          echo "header=$HEADER" >> $GITHUB_OUTPUT
      - name: Repository Alignment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/minecraft-copilot
          event-type: alignment
          client-payload: '{"branch": "${{ github.ref_name }}", "repository": "${{ github.event.repository.name }}", "message": "${{ steps.commit-message.outputs.header }}"}'
